[package]
name = "disk-saver-adapter-rust-target"
description = "disk-saver adapter for cargo target/ directories."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
disk-saver-core.workspace = true
disk-saver-platform.workspace = true
disk-saver-scan.workspace = true
serde.workspace = true
toml.workspace = true
anyhow.workspace = true
tracing.workspace = true
globset.workspace = true
humantime-serde.workspace = true

[dev-dependencies]
disk-saver-platform = { workspace = true, features = ["test-util"] }
disk-saver-kv.workspace = true
