[package]
name = "disk-saver-adapter-pnpm"
description = "disk-saver adapter for the global pnpm content-addressable store and cache."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
disk-saver-core.workspace = true
disk-saver-platform.workspace = true
disk-saver-cachedir.workspace = true
toml.workspace = true

[dev-dependencies]
disk-saver-platform = { workspace = true, features = ["test-util"] }
disk-saver-kv.workspace = true
