[package]
name = "disk-saver-adapter-trash"
description = "disk-saver adapter for the OS recycle bin / trash."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
disk-saver-core.workspace = true
disk-saver-platform.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
globset.workspace = true
humantime-serde.workspace = true

[dev-dependencies]
disk-saver-platform = { workspace = true, features = ["test-util"] }
toml.workspace = true
disk-saver-kv.workspace = true

[lints]
workspace = true
